# Generated by Django 4.0 on 2021-12-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211101_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
